// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqVHPeAMDAXDdc8C5xRrzZ1-2Whdg4uwU',
    appId: '1:625228641398:web:48fa5ad51a297cc95b1b57',
    messagingSenderId: '625228641398',
    projectId: 'auth-app-wenni',
    authDomain: 'auth-app-wenni.firebaseapp.com',
    storageBucket: 'auth-app-wenni.firebasestorage.app',
    measurementId: 'G-110FPK5H0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtk9nJ31RMZjIJldNmUo3bnkjdZAeb8fU',
    appId: '1:625228641398:android:0d28094baf6a96655b1b57',
    messagingSenderId: '625228641398',
    projectId: 'auth-app-wenni',
    storageBucket: 'auth-app-wenni.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwPtcFQIGDSMpsraHdyRfPj3dvkZV4oSo',
    appId: '1:625228641398:ios:47ae8dbcfe2f8cfc5b1b57',
    messagingSenderId: '625228641398',
    projectId: 'auth-app-wenni',
    storageBucket: 'auth-app-wenni.firebasestorage.app',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwPtcFQIGDSMpsraHdyRfPj3dvkZV4oSo',
    appId: '1:625228641398:ios:47ae8dbcfe2f8cfc5b1b57',
    messagingSenderId: '625228641398',
    projectId: 'auth-app-wenni',
    storageBucket: 'auth-app-wenni.firebasestorage.app',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqVHPeAMDAXDdc8C5xRrzZ1-2Whdg4uwU',
    appId: '1:625228641398:web:f0b4a4614c6776845b1b57',
    messagingSenderId: '625228641398',
    projectId: 'auth-app-wenni',
    authDomain: 'auth-app-wenni.firebaseapp.com',
    storageBucket: 'auth-app-wenni.firebasestorage.app',
    measurementId: 'G-58DYZHNJBF',
  );
}
